sudo: required
language: python
services:
  - docker

before_install:
  - echo "======== before install ========"
  # download and install google cloud sdk
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path/bash.inc
  - gcloud components update kubectl
  # tell sdk who we are and give it access to our account
  - gcloud auth activate-service-account --key-file service-account.json

install:
  - pip install -r myproject/requirements.txt

script:
  - python myproject/manage.py test myapp

after_success:
  - python myproject/manage.py collecstatic
  - docker build -t novskytech/djangoproject ./myproject --no-cache
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push novskytech/djangoproject:k8s

deploy:
  on:
    branch: main

after_deploy:
  - echo "======== done deploying !!!! ========"
