sudo: required
language: python
services:
  - docker
global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 

before_install:
  - echo "======== before install ========"
  # download and install google cloud sdk
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components update kubectl
  # tell sdk who we are and give it access to our account
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project django-k8s-356722
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials django-k8s

install:
  - pip install -r myproject/requirements.txt

script:
  - python myproject/manage.py test myapp

after_success:
  - python myproject/manage.py collectstatic

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    brach: master

after_deploy:
  - echo "======== done deploying !!!! ========"
